# Generated by Django 4.0.6 on 2022-07-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.CharField(max_length=20)),
                ('imagen', models.CharField(max_length=300)),
                ('titulo', models.CharField(max_length=300)),
                ('numero_parte', models.CharField(max_length=20)),
            ],
        ),
    ]
