# Generated by Django 4.0.6 on 2022-07-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_categoria_alter_products_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='categoria',
            field=models.CharField(default='', max_length=100, verbose_name='core.Categoria'),
        ),
    ]
